package com.zcurd.online.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("task_base", "id", TaskBase.class);
		arp.addMapping("task_log", "id", TaskLog.class);
		arp.addMapping("zcurd_field", "id", ZcurdField.class);
		arp.addMapping("zcurd_head", "id", ZcurdHead.class);
		arp.addMapping("zcurd_head_btn", "id", ZcurdHeadBtn.class);
		arp.addMapping("zcurd_head_js", "id", ZcurdHeadJs.class);
	}
}

