package com.zcurd.account.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysMenuDatarule<M extends BaseSysMenuDatarule<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setMenuId(java.lang.Integer menuId) {
		set("menu_id", menuId);
		return (M)this;
	}
	
	public java.lang.Integer getMenuId() {
		return getInt("menu_id");
	}

	public M setFieldName(java.lang.String fieldName) {
		set("field_name", fieldName);
		return (M)this;
	}
	
	public java.lang.String getFieldName() {
		return getStr("field_name");
	}

	public M setSymbol(java.lang.String symbol) {
		set("symbol", symbol);
		return (M)this;
	}
	
	public java.lang.String getSymbol() {
		return getStr("symbol");
	}

	public M setValue(java.lang.String value) {
		set("value", value);
		return (M)this;
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
