package com.zcurd.account.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sys_dict", "id", SysDict.class);
		arp.addMapping("sys_login_log", "id", SysLoginLog.class);
		arp.addMapping("sys_menu", "id", SysMenu.class);
		arp.addMapping("sys_menu_btn", "id", SysMenuBtn.class);
		arp.addMapping("sys_menu_datarule", "id", SysMenuDatarule.class);
		arp.addMapping("sys_oplog", "id", SysOplog.class);
		arp.addMapping("sys_role", "id", SysRole.class);
		arp.addMapping("sys_role_btn", "id", SysRoleBtn.class);
		arp.addMapping("sys_role_datarule", "id", SysRoleDatarule.class);
		arp.addMapping("sys_role_menu", "id", SysRoleMenu.class);
		arp.addMapping("sys_user", "id", SysUser.class);
	}
}

