package com.zcurd.account.model;

import java.util.List;

import com.zcurd.account.model.base.BaseSysMenuBtn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenuBtn extends BaseSysMenuBtn<SysMenuBtn> {
	public static final SysMenuBtn dao = new SysMenuBtn().dao();
	
	public List<SysMenuBtn> findAll() {
		return find("select * from sys_menu_btn");
	}
	
	public List<SysMenuBtn> findByRoleIds(String roleIds) {
		return find("select b.* from sys_role_btn a join sys_menu_btn b on a.btn_id=b.id where role_id in(" + roleIds + ")");
	}
}
