package com.zcurd.account.model;

import com.zcurd.account.model.base.BaseSysOplog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOplog extends BaseSysOplog<SysOplog> {
	public static final SysOplog dao = new SysOplog().dao();
}
