package com.zcurd.account.model;

import com.zcurd.account.model.base.BaseSysRoleBtn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleBtn extends BaseSysRoleBtn<SysRoleBtn> {
	public static final SysRoleBtn dao = new SysRoleBtn().dao();
}
